databases:
  - name: medirun-db
    databaseName: medirun
    user: medirun
    plan: free

services:
  - type: web
    name: medirun-api
    runtime: node
    plan: free
    rootDir: server
    buildCommand: npm install && node seed.js
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: medirun-db
          property: connectionString
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://medirun-mauve.vercel.app
      - key: PORT
        value: 4000
